language: node_js
node_js:
- '0.11'
branches:
  only:
  - master
env:
  global:
  - secure: 
  - secure: gc2plPur1Z0fcGl7xt8LeZvpt9TSe59YPsY5Wulu5Y060QcL5D1UYxgKLhPedXEUg02v4CUMSEOpHs28yn/hXAWh1B+sQB4hiD5Mj5XkC+jt4YGdXcXRoL9KzeLu/jwZefIilJ7AXE+IkeGrNfmWAtYUC7/HkzrEVqAIe2Vovt0T5bn88R8hS78RkfAY9EeSxmtWUJTWLe9EG2df+i3fvXEtcFMAeNbJwo3TvZgqXM5/BGLM+4VEYPz7PDXsHXpBeBS/OH2AOMCyQlL4EX1jMKPF2AduLWk9hlyKxkesJ1Z/tAL91amqymWl38o4F0L5ZMiDRPCn14yluiB9qGCHdaZDRS0SygdLBkArHHHKkOxiHL5krH3Al6mJk5p+aqdN4Wq/CA9EZdj0eSh/4Fi6n1oA/xshYUMQowDu1VBsibofu4liCAnN5q6GcVBtDymp3PlxHh5bovza+N/q5UdqbYlCRFBNWIpIHvbq8PgMjmRaCR26DtP8mboqgLwDlgUqmle6RtqXzjbHD1W5UEGYT54Y27zhH8XpjiLHg4Jo2M2B/99iij5yuuCFbrnnXbqTqc5c3IsCpOEc2NWtLkz2OgrvqXEJnAAAiO6/qP+4CFQ44nHISPCX+dso+VY9QiZkEQw33goJek3A2UqICuV/Ezt92lHEUNaCBmCuHJHCa24=
  - secure: Scx2CKNkHL2uc6mdeb/ONVDYR1SRPDPd16wzTEMcn7pXxAQoXSe9i4mGUgSzERSZTSHKelrrGjRSFRNs1MMHxHDDO64pqa44e6F6G8Ze+0wcDK5FiJPzUDBo81GHHj0MQtriq/NP/A35V6whFQY/vBVyjxXFAmrFVxu8dOXz7wrM5SURlN4uphpuaSDmAdPFYYJ8p4HIC4yqxfibgdgGyJ5/gJ+JISZ+mq8U9kLIUW218iRTcJZooqIe686xNtwEo8eUU241JeiXc+EX/EicN59n/fElfz+yeopOhuzD1uQX+gNrHal6b3WYlwmANZTSo33F2tB4lGGtunpthrpFryF+DeBm0gTqMYAP+NXbboKQsn9IYPgV61lwQ9/So8tBy0kgThlBg/MehgfeoNPpk/pWsJVfYyqzLHQdWZ9hm0wLwm9ooWO79GGrsKbLAPoS9zlwPlrEbobDzHscI3vYvFesNJFzdZAS6o14AXUdLI5WK76rg75TFv15t+6Jo2ezrnPMEitdtcal/b6na3o7mjYh42DCI6lSdZBQy3140KwjUZ21tu6F52JDQbqBprvETy+Cy4tHdT+XjF8sWmsXTQqFO+hkdva418+9c/VW37zKGBGN9IFxNFvQhHHspnCCt7er/O9SsOM+Q06oMS+Qtniv2ZgnfN8L1QCQgI4lsQc=
after_success:
- ./deploy.sh
