language: node_js
node_js:
- '0.11'
branches:
  only:
  - master
env:
  global:
    - secure: "cl5NMMDDcdaYcudK0qTBYgt7G6NuOvYkKJeEf8GSyt8+dFOOEvTF+XKHfOdPd9einMnQDP7gJIZpoRTcaPE202ySnmXuL4klofIPO0akPkgCLjXPyaYU7FZMlwhMP70ASdjRIKV/wwTr9kZPP4Mut3h7rOMYI6Etx+LfQooQmd8VUTHh9VB4Ye+FrP+KaTeTPkIfwmuVjGEusFonrnYfzrcAnckpHTKgESgaXeus17SOcV1dxYAA65AsEhIkyloKk1LNRm1LqfDqddZNUMbDP1KEIEnXd8A4okIykydlIEMD5l29DbkcTNKaLIylkzk6dCGQatCaQiKZEMLfvdAqsBkmM2hdeVhvBB3ML+vjW4WmbgTi7NMgTlxtAW1LrGBlN1itofmij2ttWq+5auSe0aJbM7RqWPwyujR537ZskKYb4Ko36RxahGC3NTiPrddTFPDfLWf7+8l6Zn3qirphEFlkNcHc/yIIS/eVL6v45ZEJmSZFNWoQtkQmeVDdtllbFuVgKsCOck8IPHOj449qc+U1DUClwnP57bXsSJNyIhGe6G2rdxz5NoxBr+6+2Fybc9gb65lOvq5tgOdHhtVvXxVmQ0JsJKN1UEmgZmrFS7jAL8qe7ZdDFuUiMiff40WB6kp2pZRz7ElDZkjNc6TGMdxhLfevoc6FxHq4ZbWJBHA="
    - secure: "Xrk69f9hH2evzQLqzOzY6PWsxzkimT+vh/VZhNC9q40SbjSm2lb6ACnNeOGyT2zaT6ybQ1kpLm0bp+aBOhsROEFaZI8XmyEkmQcT2XsTaNmX73QHA8ihfWJnsisrtbSwrN/acEoqfG5JCBJo6mFTyj8qrM+G6Ucpd69a7gWqVlp6Jz79sgCh+DoOJ7W+sWQ7D4j7Z4SPVyHqlQoS2SuKrXrrQq+pxlm6qwIdGP7+IOQI394VGGXm2Xc5FUX35g5E8pqqTZh8LHaOk4SZI0dLgaeyZeckddmemuvzOhigHfhNCKbpSWJTuRoIDtIZqFSeM3BOTLGa03FBWPriDwdQt5Lvppg8WhJfp2jmk2+mMy5EcTT7sa2QzruARf3XK4MA9HCRu3z+grGYdn2rSdtUdeEf3ndLgBPsAMgSys/X/h2R8ynRl7sRR/mBWM9Xfg/jyiCE6pk9r0jy3qNTVRIYOzNVU+vVt4IhOissKYeLwUQJ50EF59lOISqp1LZG7Gg2YEML/n/7Tg/6dXwbykYELa5G96ThpLV+tGW0ht5fNANL/DAgXvLLpctmjkrTCwMir1Citrmvt915HMp7e/p5HOdbOqAU0HW3ziPx9wKbXGsipi5/4ynkIySR0WmWiiEPpzFlXd6i3KzU2RoC2KsHXvVcDh5yCX6N+xAXjibPIQk="

 after_success:
- "./deploy.sh"
