language: node_js
node_js:
- '0.11'
branches:
  only:
  - master
env:
  global:
  - secure: mtwv040YmwIy6YWrqPSuilFTpdbtDphzJTqFcGXxjevmfR4QAw/FaU9x8LQ6lTbvpYrOagqqzszhDLfIrfJ4p7gjbqsKOEiqhLy6i36ruqUhxbWJ+7RrAURt0Uv4jyCFSykP/+Q9EcWUnsgJnc08ZKhgSJcN/q28u8hMejFGJTsROTq6eJ2FgM8LRozPGfTOIvoBRgy3pQ9O48v/GjoTEhaq9IKQZUDH08N8emTJw0R8dr6+1ZqMA/e5IQf68pZNB99a3RM5jiBo6sZqjLZ0O2RyU5bVv3j1tPAm58bDOIV9Icpmp4H0KRdTXxGWdkYZbyu6kn92NqGU5ePNHDC19w/YGXwqF6JOHiFXlJzxCA9Bop1fVATtPAlLpClAg52UsJcIBg1VEhhQNhiPLDzfI01RFo3N6qgPdI22+j8PCPCUSQxoRf4ZOnMX03fa74BN9fOMV7+qhNJ9erdkMvhBUJg2aMRKxi3ZoF7Ld6bar2NKTIgj38ZNwtsRh2iE61ajmUF5Q6SMeYKr/4pt4JxWGQHc2ATcX/Z0SmWvxRtiAUBvwzh2cDivzBR5x0V8+aIsrZMz+Ihq9NiqqjkAjCsH8lEFlX/Hy8WAUPW4j7vxRaLadthNszpG8YtlTpSc/2A/2QQjqU+UD56hXDRjOOfk+Y27XrMPb2aFy/Lve4bIk4g=
  - secure: Zq6bIn9ug7EshCrqU9qyD3HEvgZXQCt1OCVXWTKCiYqDhGoVTCpyxpyqEdPDaiI19ndNmYlKgngtG/jDmvCeddznQPChgOcTbfttUfGF3OSDHPztnR4DNxFXkwbFSqFpfbxVeufsP8v1F32s7mXvVM5xctctcEifjULh9vqWQRpcp1gjKismhn/pVnZJkz7eHQpNkkbWwfOUi54pgCJ9DhO/C/4KnbhVv/GgkuizYt+bNKRdWlFeGAsilsRZulbBr5PF2xE65XYO7MFAnGdzX/CxX16cTLNTTlLi88yNiBIDv8q+eKTZpzwfr2okLqZ1NTe8X9VbEd2qg8mQZV8oyPBUSEf+WPaVW9s45uPhit5G7sjBU0OjvzCsJHtG+l6c94pbKYCilf7lv0qRHxc2tDrqWhkl1mASuwmPsvLBc7jNYKobFJ2Qtu4mU0ZEhd8z2ZeinhW1Npc1Rffkc2SkkxqhKuWzI0n+CuYMX5/uMhrk9W1/EEDlpYdE3rQPqvsvoLRCgFfrHNd93Eaw1LPdBWbNmvmPjaFoxhCKYNP8uzo7JH3U4WRXGEDkOAmi+Qk2SJmuA1C1uQ1rn6jlvkvH0U0tcy+NSugblYU2Gt5gtyM0WuFskFQ6Au9AN337tjvCbwarkiXh/405eucAV0BkffljJzPUJ2Axwc4Zq/G1PV0=
after_success:
- "./deploy.sh"
